### 工程地址
https://github.com/andyzhaozhao/SampleJavaReactor 

### 错误处理概述
RxJava的onError跟onComplete是互斥的，出现其中任意一个事件观察者与被观察者的关系就被中断。
RXJava提供了一些处理onError事件的操作符，当被观察者Observables发送事件过程中出现了异常，可以异步发送onError事件，
从而观察者或者订阅者可以捕获到这个异常。针对这些异常可以进行一些不同的响应，如：
1. 观察者接收到异常，但是不中断，而是通知Observable继续发送接下来的数据
1. 观察者接收到异常，并且发送一个默认对象
1. 观察者接收到异常，并且立即尝试重新启动Observable，重试
1. 观察者接收到异常，并且等待一段时间后尝试重新启动Observable，重试几次

可以将这些响应分为两类：Catch和Retry。分别两篇文章进行讲解。

### Catch类响应
Catch类操作符号有；
* onErrorReturn
* onErrorReturnItem
* onErrorResumeNext
* onErrorResumeWith
* doOnError
* onErrorComplete

其中onErrorReturnItem 内部调用了 onErrorReturn ，是onErrorReturn的语法糖。
其中onErrorResumeWith 内部调用了 onErrorResumeNext。

先新建被观察者
```java
public static Observable createObservableByCreate() {
    return Observable.create(new ObservableOnSubscribe<String>() {
        @Override
        public void subscribe(@NonNull ObservableEmitter<String> observableEmitter) throws Throwable {
            observableEmitter.onNext("hello");
            observableEmitter.onNext("world");

            observableEmitter.onError(new IOException("发生了IO异常"));

            observableEmitter.onNext("1");
            observableEmitter.onNext("2");

            observableEmitter.onComplete();
        }
    });
}
```
其中`observableEmitter.onError(new IOException("发生了IO异常"));`来发送异常事件。

#### onErrorReturnItem
遇到错误，用默认数据项替代。
1. 新建订阅者，并订阅：
```java
private static void subscribe() {
    createObservableByCreate().onErrorReturnItem(100).subscribe(new Observer() {
        @Override
        public void onSubscribe(@NonNull Disposable disposable) {
            System.out.println(disposable.isDisposed());
        }

        @Override
        public void onNext(Object o) {
            System.out.println(o);
        }

        @Override
        public void onError(@NonNull Throwable throwable) {
            throwable.printStackTrace();
        }

        @Override
        public void onComplete() {
            System.out.println("完成");
        }
    });
}
```
2. 运行
```java
public static void main(String[] args) {
    subscribe();
}
```

输出：

```
false
hello
world
100
完成
```

#### onErrorReturn
出现错误的时候，用一个默认的数据项将错误替代，并立刻回调onComplete
修改：
```java
createObservableByCreate().onErrorReturn(new Function() {
        @Override
        public Object apply(Object o) throws Throwable {
            return 1000;
        }
    }).
```

#### onErrorResumeNext
onErrorResumeNext的作用就是在遇到错误时开始发射第二个Observable的数据序列
修改：
```java
createObservableByCreate().onErrorResumeNext(new Function<Throwable, ObservableSource>() {
        @Override
        public ObservableSource apply(@NonNull Throwable throwable) throws Throwable {
            //出现错误时开始发射新的Observable的数据序列
            return Observable.just(1, 2, 3);
        }
    })
```
输出：
```
false
hello
world
1
2
3
完成
```
### onErrorResumeWith
属于语法糖，不做过多讲解

#### onExceptionResumeNext
RXJava3找不到这个操作符（？）

#### onErrorComplete
RXJava3找不到这个操作符（？）

#### doOnError
这个操作符并不在官方文档的Error Handling系列中，而属于Do系列
，和Error Handling系列不同，doOnError并不会拦截异常，只是通过Action1回掉传入Thorwable，该Throwable还是会发送至onError。


