### 工程地址
https://github.com/andyzhaozhao/SampleJavaReactor 

### 错误处理Retry相关类型
retry系列是当错误的时候，重试，重新subscribe。
* retry
* retryWhen
* retryUntil

新建被观察者
```java
public static Observable createObservableByCreate() {
    return Observable.create(new ObservableOnSubscribe<String>() {
        @Override
        public void subscribe(@NonNull ObservableEmitter<String> observableEmitter) throws Throwable {
            observableEmitter.onNext("hello");
            observableEmitter.onNext("world");

            observableEmitter.onError(new IOException("发生了IO异常"));

            observableEmitter.onNext("1");
            observableEmitter.onNext("2");

            observableEmitter.onComplete();
        }
    });
}
```

#### retry次数
订阅者：
```java
private static void subscribe() {
    createObservableByCreate().retry(2).subscribe(new Observer() {
        @Override
        public void onSubscribe(@NonNull Disposable disposable) {
            System.out.println(disposable.isDisposed());
        }

        @Override
        public void onNext(Object o) {
            System.out.println(o);
        }

        @Override
        public void onError(@NonNull Throwable throwable) {
            throwable.printStackTrace();
        }

        @Override
        public void onComplete() {
            System.out.println("完成");
        }
    });
}
```

其中`.retry(2)`说明要重试两次.
运行效果
```
false
hello
world
hello
world
hello
world
java.io.IOException: 发生了IO异常
	at com.hoioy.RXJava3ErrorRetry$2.subscribe(RXJava3ErrorRetry.java:48)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:12614)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.subscribeNext(ObservableRetryPredicate.java:112)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableRetryPredicate.subscribeActual(ObservableRetryPredicate.java:41)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:12614)
	at com.hoioy.RXJava3ErrorRetry.subscribe(RXJava3ErrorRetry.java:18)
	at com.hoioy.RXJava3ErrorRetry.main(RXJava3ErrorRetry.java:14)
```
发生异常前的代码重试了两次。

### retryWhen
retryWhen的方法是根据得到的Throwable生成新的Observerable。
遇到错误时，将发生的错误传递给一个新的被观察者（Observable），
并决定是否需要重新订阅原始被观察者（Observable）& 发送事件。
```java
createObservableByCreate().retryWhen(new Function<Observable<Throwable>, ObservableSource<?>>() {
    @Override
    public ObservableSource<?> apply(@NonNull Observable<Throwable> throwableObservable) throws Throwable {
        return Observable.just(1, 2, 3,4,5,6);
    }
}).subscribe(new Observer() {
```

### retryUntil
出现错误后，判断是否需要重新发送数据。
```java
createObservableByCreate().retryUntil(new BooleanSupplier() {
    @Override
    public boolean getAsBoolean() throws Throwable {
        //true 不重试 。false，重试
        return true;
    }
}).
```